module.exports = {
  wiki: [
    'intro', 'getting-started', 'architecture', 'api', 'migration',
    'testing', 'contributing', 'roadmap',
    {type: 'category', label: 'Engineering review', items: [
      'engineering/overview', 'engineering/implementation',
      {type: 'category', label: '12 subsystem reviews', items: [{type: 'autogenerated', dirName: 'engineering/chunks'}]},
      {type: 'category', label: '32 implementation specifications', items: [{type: 'autogenerated', dirName: 'engineering/specs'}]},
      'engineering/module-index',
    ]},
  ],
};
